### ISSUE TITLE
Autocomplete not working with Turbolinks

### ISSUE THREAD

**Issue by davidbiehl** [maxivak/boostrap_autocomplete_input#2]
Is there any support for applications that use Turbolinks?

In our application, the autocomplete feature works perfectly on the initial page load. However, if we navigate to a different page, then the autocomplete simply doesn't work. There aren't any JS errors or anything. My best guess is that the event listeners aren't being registered.

Any guidance would be appreciated, in the meantime, I'm going to see if I can add the appropriate event listener for turbolinks and see if that helps us. If I get that working, I'll send a PR your way.

**Comment by maxivak** [comment]
see the solution and discussion here - https://github.com/maxivak/bootstrap3_autocomplete_input/issues/5
use 'jquery-turbolinks' gem (https://github.com/kossnocorp/jquery.turbolinks).

and have application.js file like this:

```
//= require jquery2
//= require jquery.turbolinks
//= require jquery_ujs
//= require bootstrap
//= require bootstrap3-typeahead
//= require bootstrap3-autocomplete-input.min
//= require turbolinks
```

**Comment by maxivak** [comment]
for Turbolinks - use version > 0.2.3.
and modify application.js:
```
//= require jquery2
//= require jquery_ujs
//= require bootstrap
//= require bootstrap3-typeahead.min

//= require bootstrap-autocomplete-input
//= require bootstrap-autocomplete-input-init-turbolinks

```
see readme
