### ISSUE TITLE
function autocomplete_query doesn't filter by SQL, but JS only.

### ISSUE THREAD

**Issue by blaszczakphoto** [maxivak/boostrap_autocomplete_input#3]
# Overview
I have a problem with boostrap_autocomplete_input gem. Everything works well in front-end, but when I dive into details I see that JS is triggering a query to the rails backend to fetch results to build auto complete list and it always return all records from the database table. It never filters in the backend, so it is slower than it could possible be.

# How to recreate issue
I created a clean rails project with boostrap_autocomplete_input example.
1. Run commands:
```
git clone git@github.com:blaszczakphoto/recreate_issue_in_boostrap_autocomplete_input.git`
cd recreate_issue_in_boostrap_autocomplete_input
bundle install
rake db:setup
rails server
```
2. Open in browser: http://localhost:9000/orders/new
3. Type in Client field `Marc`
4. Go to Chrome dev tools and open network tab
5. Open response preview of last get request

# Current result:
![image](https://user-images.githubusercontent.com/5549011/56729802-68866f80-6756-11e9-9a88-8ee4d683186f.png)
```
[["1","Marcin"],["2","Mariusz"],["3","Stefan"]]
```

# Desired result:
```
[["1","Marcin"],]
```

**Comment by maxivak** [comment]
it is a bug.
Thanks for your changes.
I included it in a new gem version 0.2.5
